apps/Usuario/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'usuario'

urlpatterns = [
    path('', views.registro, name='registrar'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),   
    path('excluir/<int:pk>/', views.excluir_usuario, name='excluir_usuario'),   
    path('editar/<int:pk>/', views.editar_usuario, name='editar'),
    path('lista/', views.lista, name='lista'),
]

pixelzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.Jogos.urls', namespace='jogos')),
    path('usuario/', include('apps.Usuario.urls', namespace='usuario')),
    path('genero/', include('apps.Genero.urls', namespace='genero')),
    path('reviews/', include('apps.Reviews.urls', namespace='reviews')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Usuario/models.py
from django.db import models

class Usuario(models.Model):
    nome_usuario = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=128)
    is_admin = models.BooleanField(default=False)
    imagem = models.ImageField(upload_to='usuario/', blank=True, null=True, default='usuario/default.png')
    def __str__(self):
        return self.nome_usuario

apps/Usuario/forms.py
from django import forms
from .models import Usuario

class registroform(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['nome_usuario', 'email', 'senha', 'imagem']
        widgets = {'senha': forms.PasswordInput()}

apps/Usuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import registroform
from .models import Usuario
from apps.Usuario.decorators import admin_required, login_required_custom

def registro (request):
    if request.method == 'POST':
        form = registroform(request.POST, request.FILES)
        if form.is_valid():
            usuario = form.save()
            request.session ['usuario_id'] = usuario.id
            request.session ['usuario_nome'] = usuario.nome_usuario
            request.session ['is_admin'] = usuario.is_admin
            return redirect("jogos:lista")
        
    else:
        form = registroform()
    return render(request, 'usuarios/registro.html', {'form':form, 'titulo': 'Registrar'})

def login(request):
    mensagem = ""

    if request.method == "POST":
        username = request.POST.get("nome_usuario")
        password = request.POST.get("senha")
        usuario = Usuario.objects.filter(nome_usuario=username).first()

        if usuario:
            if usuario.senha == password:
                request.session ['usuario_id'] = usuario.id
                request.session ['usuario_nome'] = usuario.nome_usuario
                request.session ['is_admin'] = usuario.is_admin
                return redirect("jogos:lista")
            else:
                mensagem = "Senha incorreta."
        else:
            mensagem = "Usuário não encontrado."

    return render(request, "usuarios/login.html", {"mensagem": mensagem,"titulo": "Login"})

def logout(request):
    request.session.flush()
    return redirect("usuario:login")

@admin_required
def lista(request):
    usuario = Usuario.objects.all()

    context = {'usuario' : usuario }
    return render(request, 'usuarios/lista.html', context)

def editar_usuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)
    if request.method == 'POST':
        form = registroform(request.POST, request.FILES, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('genero:lista')
    else:
        form = registroform(instance=usuario)
    return render(request, 'usuarios/registro.html', {'form': form, 'titulo': 'Editar Usuário'})

def excluir_usuario(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)
    if request.method == 'POST':
        usuario.delete()
        return redirect('usuario:lista')
    return render(request, 'usuarios/excluir.html', {'usuario': usuario})

apps/Usuario/templates/usuarios/excluir.html
{% extends 'base.html' %}
{% block conteudo %}

<div class="delete-container">
    <div class="delete-card">
        <h2 class="delete-title">Excluir Usuario</h2>

        <p class="delete-text">
            Tem certeza que deseja excluir o Usuário:
            <strong>"{{ usuario.nome_usuario }}"</strong>?
        </p>

        <p class="delete-warning">
            ⚠️ Esta ação não pode ser desfeita.
        </p>

        <form method="post" class="delete-actions">
            {% csrf_token %}
            <button type="submit" class="btn-delete">Sim, excluir</button>
            <a href="{% url 'jogos:lista' %}" class="btn-cancel">Cancelar</a>
        </form>
    </div>
</div>

{% endblock %}

apps/Usuario/templates/usuarios/lista.html
{% extends 'base.html' %}
{% block conteudo %}

<h1 class="title">Lista de Usuários</h1>

<div class="usuarios-container">
    {% for usuario in usuario %}
        <div class="usuario-card">
            
            <img src="{{ usuario.imagem.url }}" alt="{{ usuario.nome }}" class="avatar">

            <div class="usuario-info">
                <h1 class="nome">{{ usuario.nome_usuario }}</h1>
                <p class="email">{{ usuario.email }}</p>
            </div>

            <div class="acoes_usuario">
                <div class="acoes_u">
                    {% if request.session.is_admin %}              
                        <a href="{% url 'usuario:editar' usuario.pk %}">Editar</a>            
                        <a href="{% url 'usuario:excluir_usuario' usuario.pk %}">Excluir</a>
                    {% endif %}
                </div>
            </div>

        </div>
    {% endfor %}
</div>

{% endblock %}

apps/Usuario/templates/usuarios/login.html
{% extends "base.html" %}
{% block conteudo %}

<div class="form-container">
    <div class="form-card">
        <h1 class="form-title">{{ titulo }}</h1>

        <form method="POST" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            <p>Nome de usuário:<br>
                <input type="text" name="nome_usuario" required>
            </p>

            <p>Senha:<br>
                <input type="password" name="senha" required>
            </p>
            {% if mensagem %}
                <p style="color: red;">{{mensagem}}</p>
            {% endif %}
            <button type="submit" class="btn-enviar">Entrar</button>   
            <p class="link-auth">
                Ainda não tem uma conta?
                <a href="{% url 'usuario:registrar' %}">Registre-se</a>
            </p>                    
        </form>

    </div>
</div>

{% endblock %}

apps/Usuario/templates/usuarios/registro.html
{% extends "base.html" %}
{% block conteudo %}

<div class="form-container">
    <div class="form-card">
        <h1 class="form-title">{{ titulo }}</h1>

        <form method="POST" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn-enviar">Enviar</button>
            <p class="link-auth">
                Já possui uma conta?
                <a href="{% url 'usuario:login' %}">Faça login</a>
            </p> 
        </form>
    </div>
</div>

{% endblock %}