apps/Genero/urls.py
from django.urls import path
from . import views

app_name = 'genero'

urlpatterns = [
    path('', views.lista_generos, name='lista'),
    path('<int:pk>/', views.detalhe_genero, name='detalhe'),
    path('criar/', views.criar_genero, name='criar'),
    path('editar/<int:pk>/', views.editar_genero, name='editar'),
    path('excluir/<int:pk>/', views.excluir_genero, name='excluir'),
]

pixelzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.Jogos.urls', namespace='jogos')),
    path('usuario/', include('apps.Usuario.urls', namespace='usuario')),
    path('genero/', include('apps.Genero.urls', namespace='genero')),
    path('reviews/', include('apps.Reviews.urls', namespace='reviews')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Genero/models.py
from django.db import models

class Genero(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField(blank=True, null=True)
    imagem = models.ImageField(upload_to='generos/', blank=True, null=True)

    def __str__(self):
        return self.nome

apps/Genero/forms.py
from django import forms
from .models import Genero

class GeneroForm(forms.ModelForm):
    class Meta:
        model = Genero
        fields = ['nome', 'descricao', 'imagem']

apps/Genero/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Genero
from .forms import GeneroForm
from apps.Jogos.models import Jogo
from apps.Usuario.decorators import admin_required, login_required_custom


def lista_generos(request):
    generos = Genero.objects.all()
    return render(request, 'genero/lista.html', {'generos': generos})

def detalhe_genero(request, pk):
    genero = get_object_or_404(Genero, pk=pk)
    jogos = Jogo.objects.filter(genero=genero)

    context = {
        'genero': genero,
        'jogos': jogos
    }

    return render(request, 'genero/detalhe.html', context)

@admin_required
def criar_genero(request):
    if request.method == 'POST':
        form = GeneroForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('genero:lista')
    else:
        form = GeneroForm()
    return render(request, 'genero/form.html', {'form': form, 'titulo': 'Criar Gênero'})

@admin_required
def editar_genero(request, pk):
    genero = get_object_or_404(Genero, pk=pk)
    if request.method == 'POST':
        form = GeneroForm(request.POST, request.FILES, instance=genero)
        if form.is_valid():
            form.save()
            return redirect('genero:lista')
    else:
        form = GeneroForm(instance=genero)
    return render(request, 'genero/form.html', {'form': form, 'titulo': 'Editar Gênero'})

@admin_required
def excluir_genero(request, pk):
    genero = get_object_or_404(Genero, pk=pk)
    if request.method == 'POST':
        genero.delete()
        return redirect('genero:lista')
    return render(request, 'genero/excluir.html', {'genero': genero})

apps/Genero/templates/genero/detalhe.html
{% extends 'base.html' %}
{% block conteudo %}


<h1 class="titulo-genero">
    {{ genero.nome }}
</h1>

{% comment "" %}
<p class="descricao-genero">
    {{ genero.descricao }}
</p>
{% endcomment %}

<div class="galeria-destaque">
    {% for jogo in jogos %}
        <div class="card">

            {% if jogo.imagem %}
                <img src="{{ jogo.imagem.url }}" alt="{{ jogo.nome }}">
            {% else %}
                <img src="https://via.placeholder.com/200x225">
            {% endif %}

            <h1>{{ jogo.nome }}</h1>
            <p>{{ jogo.genero.nome }}</p>

            <div class="click">
                <a href="{% url 'jogos:detalhe' jogo.pk %}">
                    Ver detalhes
                </a>
            </div>

        </div>
    {% empty %}
        <p class="descricao-genero">
            Nenhum jogo cadastrado para este gênero.
        </p>
    {% endfor %}

</div>
<div class="acoes-g">
    <div class="acoes-genero">
        {% if request.session.is_admin %}              
            <a href="{% url 'genero:editar' genero.pk %} " class="acoes-genero">Editar</a>
            <a href="{% url 'genero:excluir' genero.pk %} " class="acoes-genero">Excluir</a>
        {% endif %}
        <a href="{% url 'genero:lista' %} " class="acoes-genero">Voltar</a>
    </div>
</div>


{% endblock %}

apps/Genero/templates/genero/excluir.html
{% extends 'base.html' %}
{% block conteudo %}

<div class="delete-container">
    <div class="delete-card">
        <h2 class="delete-title">Excluir Genero</h2>

        <p class="delete-text">
            Tem certeza que deseja excluir o gênero:
            <strong>"{{ genero.nome }}"</strong>?
        </p>

        <p class="delete-warning">
            ⚠️ Esta ação não pode ser desfeita.
        </p>

        <form method="post" class="delete-actions">
            {% csrf_token %}
            <button type="submit" class="btn-delete">Sim, excluir</button>
            <a href="{% url 'jogos:lista' %}" class="btn-cancel">Cancelar</a>
        </form>
    </div>
</div>

{% endblock %}

apps/Genero/templates/genero/form.html
{% extends "base.html" %}
{% block conteudo %}

<div class="form-container">
    <div class="form-card">
        <h1 class="form-title">{{ titulo }}</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}         
            {{ form.as_p }}

            <button type="submit" class="btn-enviar">Salvar</button>

            {% if mensagem %}
                <p style="color: red;">{{ mensagem }}</p>
            {% endif %}
        </form>
    </div>  
</div>

{% endblock %}

apps/Genero/templates/genero/lista.html
{% extends 'base.html' %}
{% block conteudo %}

<h1 class="title">Gêneros</h1>

<div class="galeria-destaque">
    {% for genero in generos %}
        <div class="card">

            {% if genero.imagem %}
                <img src="{{ genero.imagem.url }}" alt="{{ genero.nome }}">
            {% else %}
                <img src="https://via.placeholder.com/200x225">
            {% endif %}

            <h1>{{ genero.nome }}</h1>
            <p>{{ genero.descricao }}</p>
            <div class="click">
                <a href="{% url 'genero:detalhe' genero.pk %}">Ver jogos</a>
            </div>
        </div>
    {% endfor %}
</div>
<div class="acoes-g">
    <div class="acoes-genero">
        {% if request.session.is_admin %}              
            <a href="{% url 'genero:criar'%} " class="acoes-genero">Criar</a>
        {% endif %}
    </div>
</div>

{% endblock %}