apps/Jogos/urls.py
from django.urls import path
from . import views

app_name = 'jogos'

urlpatterns = [
    path('', views.lista_jogos, name='lista'),
    path('<int:pk>/', views.detalhe_jogo, name='detalhe'),
    path('criar/', views.criar_jogo, name='criar'),
    path('editar/<int:pk>/', views.editar_jogo, name='editar'),
    path('excluir/<int:pk>/', views.excluir_jogo, name='excluir'),
]

pixelzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.Jogos.urls', namespace='jogos')),
    path('usuario/', include('apps.Usuario.urls', namespace='usuario')),
    path('genero/', include('apps.Genero.urls', namespace='genero')),
    path('reviews/', include('apps.Reviews.urls', namespace='reviews')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Jogos/models.py
from django.db import models
from apps.Genero.models import Genero

class Jogo(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField()
    plataforma = models.CharField(max_length=50)
    data_lancamento = models.DateField()
    genero = models.ForeignKey(Genero, on_delete=models.CASCADE, related_name='jogos')
    imagem = models.ImageField(upload_to='jogos/')
    def __str__(self):
        return self.nome

apps/Jogos/forms.py
from django import forms
from .models import Jogo
from apps.Genero.models import Genero

class JogoForm(forms.ModelForm):
    data_lancamento = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Jogo
        fields = ['nome', 'descricao', 'plataforma', 'data_lancamento', 'genero', 'imagem']

apps/Jogos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Jogo
from .forms import JogoForm
from apps.Reviews.models import Review
from apps.Usuario.decorators import admin_required, login_required_custom

def lista_jogos(request):
    jogos = Jogo.objects.all()
    return render(request, 'jogos/lista.html', {'jogos': jogos})

def detalhe_jogo(request, pk):
    jogo = get_object_or_404(Jogo, pk=pk)
    reviews = Review.objects.filter(jogo=jogo)
    return render(request, 'jogos/detalhe.html', {'jogo': jogo, 'reviews': reviews})

@admin_required
def criar_jogo(request):
    if request.method == 'POST':
        form = JogoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('jogos:lista')
    else:
        form = JogoForm()

    return render(request, 'jogos/form.html', {'form': form,'titulo': 'Criar Jogo'})

@admin_required
def editar_jogo(request, pk):
    jogo = get_object_or_404(Jogo, pk=pk)

    if request.method == 'POST':
        form = JogoForm(request.POST, request.FILES, instance=jogo)
        if form.is_valid():
            form.save()
            return redirect('jogos:detalhe', pk=pk)
    else:
        form = JogoForm(instance=jogo)

    return render(request, 'jogos/form.html', {'form': form, 'titulo': 'Editar Jogo'})

@admin_required
def excluir_jogo(request, pk):
    jogo = get_object_or_404(Jogo, pk=pk)
    if request.method == 'POST':
        jogo.delete()
        return redirect('jogos:lista')
    return render(request, 'jogos/excluir.html', {'jogo': jogo})

apps/Jogos/templates/jogos/detalhe.html
{% extends 'base.html' %}

{% block conteudo %}

<aside class="detalhe-jogo">

    {% if jogo.imagem %}
        <img src="{{ jogo.imagem.url }}" alt="{{ jogo.nome }}" class="imagem-jogo">
    {% endif %}

    <div class="texto-aside">
        <h1>{{ jogo.nome }}</h1>

        <p><strong>Descrição:</strong> {{ jogo.descricao }}</p>
        <p><strong>Plataforma:</strong> {{ jogo.plataforma }}</p>
        <p><strong>Data de Lançamento:</strong> {{ jogo.data_lancamento }}</p>
        <p><strong>Gênero:</strong> {{ jogo.genero.nome }}</p>

        <div class="acoes">
            {% if request.session.is_admin %}
                <a href="{% url 'jogos:editar' jogo.pk %}">Editar</a>
                <a href="{% url 'jogos:excluir' jogo.pk %}">Excluir</a>
            {% endif %}
            <a href="{% url 'jogos:lista' %}">Voltar</a>
        </div>
    </div>

</aside>

<hr>

<h2 class="h2">Reviews</h2>

{% if reviews %}
    {% for review in reviews %}
        <div class="review-card">
            <div class="review-header">
                {% if review.usuario.imagem %}
                    <img src="{{ review.usuario.imagem.url }}" class="foto-perfil">
                {% endif %}               
            </div>
            <strong>{{ review.usuario.nome_usuario }}</strong>
            <p>Nota: {{ review.nota }}</p>
            <p>{{ review.comentario }}</p>
            <small>{{ review.data }}</small>
            {% if request.session.usuario_id == review.usuario.id or request.session.is_admin %}
            <div class="acoes">
                <a href="{% url 'reviews:editar' review.pk %}">Editar</a>
                <a href="{% url 'reviews:excluir' review.pk %}">Excluir</a>
            </div>
            {% endif %}
        </div>
    {% endfor %}

{% else %}
        <div class="review-card">
            <p>Este jogo ainda não possui reviews.</p>
        </div>
    
{% endif %}

<div class="acoes-g">
    <div class="acoes-genero">
        <a href="{% url 'reviews:criar' jogo.pk %}">Adicionar Review</a>
    </div>
</div>

{% endblock %}

apps/Jogos/templates/jogos/excluir.html
{% extends 'base.html' %}
{% block conteudo %}

<div class="delete-container">
    <div class="delete-card">
        <h2 class="delete-title">Excluir Jogo</h2>

        <p class="delete-text">
            Tem certeza que deseja excluir o jogo:
            <strong>"{{ jogo.nome }}"</strong>?
        </p>

        <p class="delete-warning">
            ⚠️ Esta ação não pode ser desfeita.
        </p>

        <form method="post" class="delete-actions">
            {% csrf_token %}
            <button type="submit" class="btn-delete">Sim, excluir</button>
            <a href="{% url 'jogos:lista' %}" class="btn-cancel">Cancelar</a>
        </form>
    </div>
</div>

{% endblock %}

apps/Jogos/templates/jogos/form.html
{% extends "base.html" %}
{% block conteudo %}

<div class="form-container">
    <div class="form-card">
        <h1 class="form-title">{{ titulo }}</h1>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}         
            {{ form.as_p }}

            <button type="submit" class="btn-enviar">Salvar</button>

            {% if mensagem %}
                <p style="color: red;">{{ mensagem }}</p>
            {% endif %}
        </form>
    </div>
</div>

{% endblock %}

apps/Jogos/templates/jogos/lista.html
{% extends 'base.html' %}
{% block conteudo %}



<div class="galeria-destaque">
    {% for jogo in jogos %}
        <div class="card">

            {% if jogo.imagem %}
                <img src="{{ jogo.imagem.url }}" alt="{{ jogo.nome }}">
            {% else %}
                <img src="https://via.placeholder.com/200x225" alt="Sem imagem">
            {% endif %}

            <h1>{{ jogo.nome }}</h1>
            <p>{{ jogo.genero.nome }}</p>

            <div class="click">            
                <a href="{% url 'jogos:detalhe' jogo.pk %}">Ver detalhes</a>
            </div>

        </div>
    {% endfor %}
</div>
<div class="acoes-g">
    <div class="acoes-genero">
        {% if request.session.is_admin %}              
            <a href="{% url 'jogos:criar'%} " class="acoes-genero">Criar</a>
        {% endif %}
    </div>
</div>

{% endblock %}